### ISSUE TITLE
Want to make a phone call service through my app

### ISSUE THREAD

**Issue by hssn-hassnain** [AseemWangoo/services_demo#2]
hi thankyou for the new thing. I want to perfoam a Phone call through my app by using Flutter UI. for that i want to right a class at the native side can You help me In this to let me know how i can Perfoam this feature by using this service demo. Currently i see it is for the alarm.

**Comment by AseemWangoo** [comment]
Hello,

Will take a look into it, who knows if this may be one of the upcoming
articles :)


* Stay healthy !!*
 Aseem Wangoo *Software Engineer*

   - Mobile (SG) : +65 9615 6442


   -   Email : aseemwangoo@gmail.com
   - Website: https://flatteredwithflutter.com/

**Comment by AseemWangoo** [comment]
Hello @hssn-hassnain, were you able to accomplish the phone service?
