### ISSUE TITLE
COMPILE TIME ERROR: There's no constant named 'suspending' in 'AppLifecycleState'. Try correcting the name of existing constant, or defining a constant named 'suspending'

### ISSUE THREAD

**Issue by UsabilitySpace** [AseemWangoo/services_demo#3]
**Your code won't compile due to next minor error:** 

- There's no constant named 'suspending' in 'AppLifecycleState. Try correcting the name of existing constant, or defining a constant named 'suspending'.

**The image of the error:** 

![image](https://user-images.githubusercontent.com/46682521/91041205-d0dead00-e639-11ea-8b35-4105024e0a43.png)

**The error mentioned appears because of this:**

- AppLifecycleState.suspending changed to AppLifecycleState.detached.

**So, to make your code compile properly, correct your code here:** 

- main.dart > didChangeAppLifecycleState() > near line 97.

**... by replacing this lines:** 

```
    if (state == AppLifecycleState.paused || 
        state == AppLifecycleState.suspending 
        ) {
    ...
```
**... with this lines:** 

```
    if (state == AppLifecycleState.paused || 
        state == AppLifecycleState.detached 
        ) {
    ...
```

**Comment by AseemWangoo** [comment]
Thanks for the suggestion. Will do it during upgrading
