### ISSUE TITLE
FLUTTER ENVIRONMENT RUN TIME ERROR: Hot Restart Error: hot restart failed to complete: resume: (105) Isolate must be runnable before this request is made. 

### ISSUE THREAD

**Issue by UsabilitySpace** [AseemWangoo/services_demo#6]
**When trying to reload or hot reload the project using android studio + android emulator, android studio throws such an error:** 

```
Hot Restart Error: 
hot restart failed to complete: resume: (105) Isolate must be runnable 
Isolate must be runnable before this request is made. 
```

**Image of the error:** 

![image](https://user-images.githubusercontent.com/46682521/91040659-cff94b80-e638-11ea-8ae9-81a18e5fe6f8.png)

**The error thrown may be produced by the way the code handles the app's lifecycle (_or my be not_).**

**Please check the error and make suggestion should it be handled and if so.**

**Comment by AseemWangoo** [comment]
Thanks for pointing out. Will have a look into it, in case you have find the solution, kindly create PR and I can merge it ☺️
